# -*- coding: utf-8 -*-
"""Rock-paper-scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dz3LDlubnt7J-dAHNUDMZRVrDdGaDnuw
"""

import random

#โปรแกรมเป่ายิ้งฉุบ 

print("- Let's play Rock paper scissors ! -")
print("============rules============")
print("press r for rock")
print("press p for paper")
print("press s for scissors")
print("===========================")
#อธิบายกฎ กติกาการเล่น

#user ใส่ข้อมูลตัวอักษรที่ต้องการจะเป่ายิ้งฉุบ แล้วแสดงค่าออกมาว่า user เลือกอะไร
user_turn = input("your turn : ")
if user_turn == 'r'  :
  print("ROCK")
elif user_turn == 'p' :
  print("PAPER")
elif user_turn == 's' :
  print("SCISSORS")


#random ว่าคอมพิวเตอร์จะออกอะไรแล้วแสดงค่าออกมา
#ใช้ random.choice เพื่อสุ่มแบบเลือกจากลิสต์ที่เรากำหนดไว้
computer_turn = random.choice(['r','p','s'])
if computer_turn == 'r'  :
  print("computer turn : ROCK")
elif computer_turn == 'p' :
  print("computer turn : PAPER")
elif computer_turn == 's' :
  print("computer turn : SCISSORS")

#นำค่าทั้งสองมาเปรียบเทียบกัน แล้วแสดงผล
if user_turn == computer_turn :
  print("DRAW")
elif user_turn == 'r' and computer_turn == 'p' :
  print("LOSE")
elif user_turn == 'r' and computer_turn == 's' :
  print("WIN")
elif user_turn == 'p' and computer_turn == 's' :
  print("LOSE")
elif user_turn == 'p' and computer_turn == 'r' :
  print("WIN")
elif user_turn == 's' and computer_turn == 'r' :
  print("LOSE")
elif user_turn == 's' and computer_turn == 'p' :
  print("WIN")